FROM nms_base_image AS build
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod verify
RUN go mod download  
COPY . .
RUN go test ./test2 -c -o test_program
RUN cd /build/test1/mainprogram &&\
 go run mainprogram.go &&\
 go build -o mainprogram mainprogram.go 
FROM alpine:latest AS integration_test 
WORKDIR /app/
COPY --from=build /build/test_program ./ 
COPY --from=build /build/test1/mainprogram ./
COPY --from=build /build/test1/mainprogram ./mainprogram2
RUN chmod 755 ./mainprogram2
COPY --from=build /build/entrypoint.sh ./
COPY --from=build /build/testintegration.sh ./
RUN chmod 755 /app/entrypoint.sh
RUN chmod 755 /app/testintegration.sh
CMD ["/app/entrypoint.sh"]
