FROM golang:1.18.3-bullseye AS build_base_image
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod verify
RUN go mod download  
# install protoc & grpc-gateway 
RUN apt-get update \
    && apt-get install -y protobuf-compiler
RUN go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway\
    && go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2\
    && go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1\
    && go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.27\
    && go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger\
    && go get github.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor@v2.10.0
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway\
    && go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2\
    && go install google.golang.org/protobuf/cmd/protoc-gen-go\
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
RUN mkdir -p google/api 
RUN curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto > google/api/annotations.proto 
RUN curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/http.proto > google/api/http.proto
RUN export PATH="$PATH:$(go env GOPATH)/bin"

