FROM nms_base_image AS build
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod verify
RUN go mod download  
COPY . .
RUN go test ./test2 -c -o test_program
RUN cd /build/test1/mainprogram &&\
 go run mainprogram.go &&\
 go build -o mainprogram mainprogram.go 
# TODO - can't get version in container
FROM build AS test 
WORKDIR /test
COPY --from=build /build ./
RUN cd /test/test2 &&\
 go test 
RUN ./test_program